### ISSUE TITLE
problems with line endings in cygwin

### ISSUE THREAD

**Issue by ghost** [gatblau/europa#5]
Still getting these errors:

`fetch.sh: line 3: $'\r': command not found 
`fetch.sh: line 5: $'\r': command not found 
`fetch.sh: line 18: syntax error near unexpected token`$'{\r'' 
`'etch.sh: line 18:`remove_empty_files() {

According to [this page](https://chess.eecs.berkeley.edu/softdevel/faq/5.html), cygwin needs to be configured to ignore carriage returns. Except the instructions are wrong. Need to add these commands to .bash_profile:

set -o igncr
export SHELLOPTS

Should add this to instructions for windows installs.

**Comment by gatblau** [comment]
Run the dos2unix command on the file in question.
I now provide binaries for the releases so there is no need to build from source anymore.
